### ISSUE TITLE
Feedback Report Error

### ISSUE THREAD

**Issue by prathip111** [hakanensari/peddler#106]
I'm trying to pull amazon feedback API (_GET_SELLER_FEEDBACK_DATA_) but i am getting error response Done_No_Data but I'm getting data manually submitting the report from amazon seller central.

**_Submitting Request:-_**

client = MWS::Reports::Client::new(
  primary_marketplace_id: "A21TJRUU*****",
  merchant_id: "A1EX79S*******",
  aws_access_key_id: "AKIAJPPWNF**********",
  aws_secret_access_key: "ovxM8XKOb67kKg1/sqx26yNBj***************",
)

 response = client.request_report("_GET_SELLER_FEEDBACK_DATA_")
 
data = response.parse

**_Getting Response:-_**

 {"HasNext"=>"true", "ReportRequestInfo"=>[{"ReportType"=>"_GET_SELLER_FEEDBACK_DATA_", "ReportProcessingStatus"=>"_DONE_NO_DATA_", "EndDate"=>"2018-02-24T05:40:28+00:00", "Scheduled"=>"false", "ReportRequestId"=>"50563017586", "StartedProcessingDate"=>"2018-02-24T05:40:33+00:00", "SubmittedDate"=>"2018-02-24T05:40:28+00:00", "StartDate"=>"2018-02-24T05:40:28+00:00", "CompletedDate"=>"2018-02-24T05:40:39+00:00"}

**Comment by prathip111** [comment]
Can you please help me how can i get negative feedback throw API using your gem file in rails..

**Comment by hakanensari** [comment]
This is not related to the gem.

In any case, report type looks incorrect, try `_GET_SELLER_FEEDBACK_DATA_`.

**Comment by prathip111** [comment]
Thanks for your immediate response...but i have an issue mention below..

I used the above method but i'm not able to get generated report data, It showing "DONE_NO_DATA". But if i pulling manually i got the correct report with data.

Issue Images:-

The images shows the difference between manually generated reports and peddler generated reports:-

![issue peddler 1](https://user-images.githubusercontent.com/30593672/36653592-2626fde8-1adc-11e8-80a7-0cd00ff7d354.jpg)

![issue peddler 1 con](https://user-images.githubusercontent.com/30593672/36653590-2581ac9e-1adc-11e8-87c0-02efb6ede51a.jpg)


When i parsed the response i got (done_no_data) but issue is data available in seller dashboard:- 

![issue peddler](https://user-images.githubusercontent.com/30593672/36653594-26b6ae02-1adc-11e8-9d5b-2de399b2f3c9.jpg)

**Comment by prathip111** [comment]
Bro please help me

**Comment by hakanensari** [comment]
I see what the issue is &mdash; MWS seems to default the optional `start_date` to now, which is not what you want here.

You can see what happened in the `Date Range Covered` column: you basically generated a report for a particular point in time rather than a range.

Long story short, you should be fine if you specify a `start_date` when requesting the report.

I should have possibly specified default values in the source code documentation.

**Comment by prathip111** [comment]
Thank you for the response its working perfectly now... Appreciate your time and effort

**Comment by prathip111** [comment]
I need another help,  I facing throttling issue in 'VACUUM' gem (It occurs when i request more than 10 queries in a loop)

request = Vacuum.new('IN')

request.configure(
  aws_access_key_id: 'AKIAJGAXOKAK********',
  aws_secret_access_key: 'yPWtg3vMUTDX5IP0Ko8VJ********************',
  associate_tag: 'pen*********'
)



response = request.item_lookup(
  query: {
    'ItemId' => '1937707881',
    'ResponseGroup' => 'Large'
  }
)
