### ISSUE TITLE
Country codes.

### ISSUE THREAD

**Issue by alexfalkowski** [hakanensari/peddler#110]
Hi,

This is a question regarding the changes in 2.0. When I do 

```ruby
[1] pry(main)> Peddler::Marketplace.all.map { |m| m.country_code }
=> ["CA", "MX", "US", "BR", "DE", "ES", "FR", "IT", "GB", "IN", "AU", "JP", "CN"]
```

I no longer have `UK` but it has been replaced with `GB`. According to this https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html it should be `UK`. Was just wondering why the change as this impacts us.

**Comment by hakanensari** [comment]
Wow, you noticed this 😮 

I ended up sticking to [standard country codes](https://en.wikipedia.org/wiki/ISO_3166-2)  but added a [guard](https://github.com/hakanensari/peddler/blob/master/lib/peddler/marketplace.rb#L25) to accommodate `UK` as well, so all should be good.

**Comment by alexfalkowski** [comment]
@hakanensari - yes I noticed cause we wrote out own `find_by_country_code`. Will user your new find then.
