### ISSUE TITLE
Get Orders doesn't work for multiple orders 

### ISSUE THREAD

**Issue by prathip111** [hakanensari/peddler#111]
response = client.get_order("XXX-1236548-4587XXX", "XXX-1546987-7845XXX")
order = response.parse

The documentation says it can take upto 50 orders as input..but while 'response' has info for all 50 orders, once it's parsed, only the first order seems to show.

**Comment by hakanensari** [comment]
@prathip111 I'm not sure, everything looks in order in [the test](https://github.com/hakanensari/peddler/blob/master/test/integration/test_orders.rb#L7-L22).

**Comment by prathip111** [comment]
your testing code is working fine thanks a lot...
