### ISSUE TITLE
Looking like Australia hasn't been added to the gem?

### ISSUE THREAD

**Issue by Trimakas** [hakanensari/peddler#120]
Hi,
Amazon recently enabled the Australian FBA marketplace, but it looks like the gem hasn't been updated with the marketplace yet. The Australian marketplace id is: A39IBJ37TRP1C6

According to [Amazon here](http://docs.developer.amazonservices.com/en_IN/dev_guide/DG_Endpoints.html)

Because when I try to connect I'm getting this error:

`"A39IBJ37TRP1C6" is not a valid MarketplaceId (Peddler::Marketplace::BadId)`

**Comment by Trimakas** [comment]
And by the way, lovely gem, thank you so much!!

**Comment by hakanensari** [comment]
The latest gem does support Australia. Perhaps you have an earlier version?

**Comment by Trimakas** [comment]
Yes it does.. thanks for getting back to me!
