### ISSUE TITLE
Not an issue, just a question

### ISSUE THREAD

**Issue by Trimakas** [hakanensari/peddler#125]
Hi,
I have all my customers subscribed to the `FulfillmentOrderStatusNotification`  But I'm suddenly not getting all the messages when an order is shipped. It's very random and only happens when the order is fulfilled. 

Any idea how to deal with missing/not sent messages in the SQS queue?

Thanks
Todd

**Comment by hakanensari** [comment]
@Trimakas I'm not sure. It sounds like you may be silently skipping over some notifications by mistake, assuming you are popping everything off the SQS queue?

**Comment by Trimakas** [comment]
@hakanensari yep i am.. I even created a dead message queue.. but nothing.. super weird.. can't figure it out
