### ISSUE TITLE
Quantity updated on both US and CA even though only CA was specified

### ISSUE THREAD

**Issue by noorani786** [hakanensari/peddler#129]
I submitted Price & Quantity feed and specified just CA marketplace 'A2EUQ1WTGCTBG2'.  The SKU exists on both marketplaces.  Instead of quantity updating on just Amazon CA, quantity changed on both US and CA.  Ran it multiple times and got the same result.  Please look into this.

**Comment by hakanensari** [comment]
This sounds like what the API is supposed to do. Perhaps you need to [limit the marketplace with a keyword](https://github.com/hakanensari/peddler/blob/master/lib/mws/feeds/client.rb#L22)?

**Comment by noorani786** [comment]
I am passing marketplace_id_list => 'A2EUQ1WTGCTBG2' so it only affects CA.  Shouldn't that limit to the just CA?  Can you elaborate what you mean by keyword?  Thanks!

**Comment by hakanensari** [comment]
Yes, that's what I meant. So you're still ending up uploading the feed to both marketplaces?

You can inspect what the request looks like by setting `EXCON_DEBUG=1` in the environment. If the parameters are fine, I'd suggest following up with the MWS team.
