### ISSUE TITLE
Where to find merchant_id?

### ISSUE THREAD

**Issue by andrewhavens** [hakanensari/peddler#132]
Sorry if this question is really simple. I can't seem to find our `merchant_id`. I found something in our account info called a "Merchant Token"...is that the same thing? (I'm trying to build an application that will be used internally. It won't be distributed through the "App Store")

**Comment by hakanensari** [comment]
Amazon displays your merchant ID on the page where they reveal your MWS credentials (AWS keys etc.)

The [help pages](https://docs.developer.amazonservices.com/en_UK/dev_guide/DG_Registering.html) should guide you in case you have trouble finding this.

**Comment by andrewhavens** [comment]
Hmm...the page that you are referring to only shows the "Developer ID"...is that the same thing?

<img width="630" alt="Screen Shot 2019-06-11 at 10 29 08 AM" src="https://user-images.githubusercontent.com/446392/59293513-2d6fcb00-8c34-11e9-8104-a0cd547754e9.png">

**Comment by hakanensari** [comment]
It seems they made some changes and inadvertently removed the option to request MWS credentials to access your own account. As a workaround, you could add yourself as a third-party app using that developer ID. This should take you to a final page where they display the merchant (seller) ID.

Let me know if you get in touch with Seller Support and find out more on this. We could update the README as this will possibly be a pain point for other new MWS users as well.

**Comment by andrewhavens** [comment]
I tried simply using the "Merchant Token" and it seems to be working. Maybe they just renamed it.

<img width="947" alt="Screen Shot 2019-06-12 at 5 29 21 PM" src="https://user-images.githubusercontent.com/446392/59395290-0d293480-8d38-11e9-9c90-99a53ea4582f.png">


<img width="712" alt="Screen Shot 2019-06-12 at 5 29 42 PM" src="https://user-images.githubusercontent.com/446392/59395268-f2ef5680-8d37-11e9-95c7-810d39ba84ad.png">

Learn more link goes to this page: https://sellercentral.amazon.com/gp/help/48321?ref_=macs_48321_cont_aimertok
