### ISSUE TITLE
Ability to mark an order as fulfilled (+ submit carrier tracking number)

### ISSUE THREAD

**Issue by hemaldev** [hakanensari/peddler#134]
Hi there,

Firstly, thanks for the gem – I'm volunteering with a non-profit organisation in South India that makes handmade paper and we are currently dipping our toe into Amazon's US marketplace. We are adding around 1k+ SKUs from our ecommerce platform (which powers our Etsy shop) built in Rails and your gem looks like it will make things a breeze for us on Amazon.

We need to do 3 things and were wondering if you could point us in the right direction for a couple of things:
1. Get open orders: It looks like `MWS::Orders::Client#list_orders` will do the trick, so I think we're ok here
2. Update our inventory: `MWS::Feeds::Client#submit_feed` looks like the way to go – we were wondering if you had a handy way to generate the XML from a basic ruby object/bit of json with the required sku and inventory data?
3. Mark orders as shipped: We couldn't see anything in the documentation about doing this, would we need to `submit_feed` with a `MessageType` of `OrderFulfillment`?

Thanks once again for the gem, any pointers you can provide would go a long way.

❤️

**Comment by hakanensari** [comment]
@hemaldev I'm sure you have figured out the answers, but I'll chime in.

1. Yes
2. I did not want to hard code any XML library as a dependency, so you will  have to implement this yourself. Alternatively, you can send a flat file if that feels more convenient to build.
3. Off the top of my head, you will want to send an [order fulfilment feed](https://docs.developer.amazonservices.com/en_US/feeds/Feeds_FeedType.html) to handle shipment confirmations, refunds, and so on.

Good luck on the project

**Comment by hemaldev** [comment]
@hakanensari Thanks for the heads up on these points. We paused the project as we're still waiting to be approved by Amazon for access to the API. Do you happen to have a contact there who might be able to help? Any help or pointers much appreciated...

**Comment by hakanensari** [comment]
@hemaldev, sorry, no. Keep hammering on their door.
