### ISSUE TITLE
`get_feed_submission_result` returns nil

### ISSUE THREAD

**Issue by nandhini08** [hakanensari/peddler#140]
when I try the request  `get_feed_submission_result` I get nil response. 
```
@client = MWS.feeds(
      marketplace: "US"
      merchant_id: XXX,
      auth_token: XXX
      aws_access_key_id: XXX,
      aws_secret_access_key: XXX,
     )

@result_response = @client.get_feed_submission_result('124413018184')
```
However for the same feed ID I tried from Amazon Scratchpad and I get proper response. 
![Screenshot 2019-10-15 at 10 14 30 PM](https://user-images.githubusercontent.com/32125751/66851807-303f4b80-ef99-11e9-9272-3c38bd74d1fe.png)

**Comment by nandhini08** [comment]
@hakanensari any idea why I am facing this issue

**Comment by hakanensari** [comment]
@nandhini08 are you by any chance using an older version of Peddler? There was a fix in the parser a couple of years ago for this response type.
