### ISSUE TITLE
InvalidMarketplace error from Amazon turns into a parse error

### ISSUE THREAD

**Issue by marytal** [hakanensari/peddler#145]
Hey!
I'm attempting to submit an inventory update feed, but the account I'm submitting it for is suspended. Instead of getting `Peddler::Errors::InvalidMarketplace`, I see `ArgumentError · wrong number of arguments (given 2, expected 0..1)`

I cannot rescue `Peddler::Errors::InvalidMarketplace` (even though I've defined the error in my repo) because I'm thinking the parsing error happens before it gets translated. 

```
# frozen_string_literal: true
module Peddler
  module Errors
    class InvalidMarketplace < StandardError; end
  end
end
```

Feed Response (through ScratchPad)
```
<?xml version="1.0"?>
<ErrorResponse xmlns="http://mws.amazonaws.com/doc/2009-01-01/">
<Error>
  <Type>Sender</Type>
  <Code>InvalidMarketplace</Code>
  <Message>Feed rejected</Message>
  <Detail/>
</Error>
<RequestID>[REDACTED]</RequestID>
</ErrorResponse>
```

Steps to reproduce:
* Use a suspended Seller Central account and attempt to submit an inventory update feed

Thanks for your help (and this gem)!

**Comment by hakanensari** [comment]
What line is throwing that error—could you paste here the traceback?

**Comment by marytal** [comment]
Sorry, here it is:
```
from vendor/bundle/ruby/2.6.0/gems/peddler-2.3.0/lib/peddler/errors/builder.rb:34:in `new'
    from vendor/bundle/ruby/2.6.0/gems/peddler-2.3.0/lib/peddler/errors/builder.rb:34:in `build'
    from vendor/bundle/ruby/2.6.0/gems/peddler-2.3.0/lib/peddler/errors/builder.rb:20:in `call'
    from vendor/bundle/ruby/2.6.0/gems/peddler-2.3.0/lib/peddler/client.rb:152:in `handle_http_status_error'
    from vendor/bundle/ruby/2.6.0/gems/peddler-2.3.0/lib/peddler/client.rb:121:in `rescue in run'
    from vendor/bundle/ruby/2.6.0/gems/peddler-2.3.0/lib/peddler/client.rb:113:in `run'
    from vendor/bundle/ruby/2.6.0/gems/peddler-2.3.0/lib/mws/feeds/client.rb:118:in `get_feed_submission_result'
```

**Comment by hakanensari** [comment]
```ruby
# frozen_string_literal: true
module Peddler
  module Errors
    class InvalidMarketplace < StandardError; end
  end
end
````

It's a type error. You need to inherit from `Peddler::Errors::Error`, not `StandardError`. I added a guard to alert about this in runtime, which should make things more resilient.

**Comment by marytal** [comment]
Thank you!!
