### ISSUE TITLE
Report 'GET_XML_BROWSE_TREE_DATA'  - Parser - XML - Nil

### ISSUE THREAD

**Issue by leoplct** [hakanensari/peddler#151]
I am requesting the '_GET_XML_BROWSE_TREE_DATA_' report.
`self.downloadReport('_GET_XML_BROWSE_TREE_DATA_',` options: {report_options: "BrowseNodeId=454824031"})`

I can successfully retrieve the report .inspect()

```
puts "DATA: #{client.get_report(report_id).inspect}"
```
> DATA: #<Excon::Response:0x00007f8c82a636a8 @data={:body=>"<Result>\n<query>454824031</query>\n<Node>\n<browseNodeId>454824031</browseNodeId>\n<browseNodeAttributes count=\"1\">\n<attribute name=\"recommended_browse_nodes\">454824031</attribute>\n</browseNodeAttributes>\n<browseNodeName>Soft Rifle Cases</browseNodeName>\n<browseNodeStoreContextName>Soft Rifle 

but if I execute puts report.parse() returns 

> nil

**Comment by hakanensari** [comment]
@leoplct Thanks for reporting, the above commit should fix this
