### ISSUE TITLE
Did you know the Peddler docs aren't there anymore?

### ISSUE THREAD

**Issue by Trimakas** [hakanensari/peddler#156]
They just fail.. 

See this as an example.

https://www.rubydoc.info/gems/peddler/MWS/FulfillmentInventory/Client

Not sure what's up?

**Comment by gbs4ever** [comment]
same problem for me

**Comment by hakanensari** [comment]
🤷 

[GitHub-triggered docs][1] seem to be generating fine; seems like [a heisenbug][2] on their end?

[1]: https://www.rubydoc.info/github/hakanensari/peddler
[2]: https://github.com/lsegal/yard/issues/1146
