### ISSUE TITLE
get_capture_details doesn't work

### ISSUE THREAD

**Issue by dawnd80** [hakanensari/peddler#30]
Hi there, I can't seem to call get_capture_details to work. I looked into the source code:

def get_capture_details(amazon_capture_id)
        operation('GetAuthorizationDetails')
          .add('AmazonCaptureId' => amazon_capture_id)
       run
end

Should the operation be set to GetCaptureDetails? Thanks!

**Comment by hakanensari** [comment]
Thanks @dawnd80
