### ISSUE TITLE
Using AuthToken gives 'missing secret' error

### ISSUE THREAD

**Issue by philsmy** [hakanensari/peddler#31]
Using the code from the read me on how to access another seller's mws (having been given there mws auth token) we get:
`ArgumentError: Missing secret`
from the Jeff library. That lib seems to require a secret.
I don't know if this is a bug with the jeff lib, but, as the read me implies this is working I think it is a bug inside here.

**Comment by hakanensari** [comment]
You still have to use your own AWS key and secret in conjunction with the seller's auth token.

**Comment by philsmy** [comment]
Great! I'm going to give that a try.
So in fact it is:

`client = MWS.orders(
  marketplace_id: "...",
  merchant_id:    "...",
  auth_token:     "...",
  aws_access_key_id:     "...",
  aws_secret_access_key: "..."
)

**Comment by hakanensari** [comment]
That's correct.

**Comment by systemnate** [comment]
Just to confirm: You should pass YOUR (the developer's) marketplace_id, merchant_id, aws_access_key_id, and aws_secret_access_key, and you only need the user's auth_token?  Thanks in advance!

**Comment by hakanensari** [comment]
@systemnate: It's your AWS Access Key ID and AWS Secret Access Key only. Rest is the user's.

**Comment by systemnate** [comment]
Thanks!
