### ISSUE TITLE
Error codes aren't helpful

### ISSUE THREAD

**Issue by jmcmains** [hakanensari/peddler#32]
Running into a lot of issues where the connection will just fail, and I'll get a 
"Excon::Errors::BadRequest: Expected(200) <=> Actual(400 Bad Request)"

I'm working mostly with creating new shipment plans and shipments. After digging for an hour I figured out that one of my skus (out of about 50) didnt have dimensions entered. Any way this error flow can be improved?

**Comment by hakanensari** [comment]
While it won't relieve your earlier pain, take a look at the undocumented [`Client#on_error`](https://github.com/hakanensari/peddler/blob/master/lib/peddler/client.rb#L79-L81) hook.

I will leave this issue open until I add relevant documentation to the README and source. Also, I should possibly consider mirroring this method on the class level so users can define a universal error handler.
