### ISSUE TITLE
BadID

### ISSUE THREAD

**Issue by viperouge** [hakanensari/peddler#34]
I was trying to set up peddler and after I put my marketplace_id, merchant_id etc and start the server the following error is returned: gems/peddler-0.12.7/lib/peddler/marketplace.rb:44:in `block in find_host': Peddler::Marketplace::BadId (Peddler::Marketplace::BadId)

I'm using Ruby 2.1.3 and Rails 4.2.0

Any ideas how to fix it?

**Comment by hakanensari** [comment]
It sounds like you didn't set the `marketplace_id` on the client or you set it to something not in [here](https://github.com/hakanensari/peddler/blob/master/lib/peddler/marketplace.rb#L5-L14)?

**Comment by viperouge** [comment]
I did.. my marketplace id is:

  marketplace_id:        "ATVPDKIKX0DER"

**Comment by viperouge** [comment]
in which files should I place:

**Comment by hakanensari** [comment]
I added a descriptive message to the `Marketplace::BadId` error. Could you point your `Gemfile` to the GitHub repo and see what the error message says?

**Comment by viperouge** [comment]
missing MarketplaceId (Peddler::Marketplace::BadId). Currently the ID is in a file called peddler.rb in config/initializers. Maybe I'm just doing something wrong?

**Comment by hakanensari** [comment]
Looks like it. You need to set the credentials each time you instantiate a client. There's no singleton configuration object that stores credentials across instances.

If you are using a single set of credentials, I recommend you set them through environment variables, as I explain in the README.

I'll keep this issue open until I get a chance to reword the README to make this more explicit.
