### ISSUE TITLE
requested_to_date filter not working as suspected

### ISSUE THREAD

**Issue by gardart** [hakanensari/peddler#37]
Just wanted to say thanks for developing this, it has helped me a lot getting useful data from Amazon.

Im using Peddler 0.15.0 and Im trying to get report request list by using :requested_to_date and :requested_from_date as filters. It seems to me that the requested_to_date is filtering agains the "SubmittedDate" rather than the EndDate. (see my testing below).

In the documentation, http://docs.developer.amazonservices.com/en_US/reports/Reports_GetReportRequestList.html
the description for the RequestedToDate variable is:
"The end of the date range used for selecting the data to report, in ISO8601 date format."

Is this a bug ? Or am I misunderstanding here :)

Testing results
Report info:
 => {"ReportRequestInfo"=>{"StartDate"=>"2015-04-20T00:00:00+00:00", "CompletedDate"=>"2015-04-21T10:09:22+00:00", "Scheduled"=>"false", "ReportType"=>"_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_", "GeneratedReportId"=>"56688023803", "ReportProcessingStatus"=>"_DONE_", "SubmittedDate"=>"2015-04-21T10:08:57+00:00", "EndDate"=>"2015-04-20T23:59:59+00:00", "StartedProcessingDate"=>"2015-04-21T10:09:14+00:00", "ReportRequestId"=>"50366016546"}, "HasNext"=>"false"}

Test with :requested_to_date < "SubmittedDate" => Returns no data
1.9.3-p551 :048 > test=client_reports.get_report_request_list(:report_type_list=>"_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_", :requested_from_date=>1.day.ago.midnight, :report_processing_status_list=>"_DONE_", :requested_to_date=>"2015-04-21T10:08:56+00:00").parse
 => {"HasNext"=>"false"}

Test with :requested_to_date = "SubmittedDate" => Returns data
1.9.3-p551 :049 > test=client_reports.get_report_request_list(:report_type_list=>"_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_", :requested_from_date=>1.day.ago.midnight, :report_processing_status_list=>"_DONE_", :requested_to_date=>"2015-04-21T10:08:57+00:00").parse

 => {"ReportRequestInfo"=>{"StartDate"=>"2015-04-20T00:00:00+00:00", "CompletedDate"=>"2015-04-21T10:09:22+00:00", "Scheduled"=>"false", "ReportType"=>"_GET_AMAZON_FULFILLED_SHIPMENTS_DATA_", "GeneratedReportId"=>"56688023803", "ReportProcessingStatus"=>"_DONE_", "SubmittedDate"=>"2015-04-21T10:08:57+00:00", "EndDate"=>"2015-04-20T23:59:59+00:00", "StartedProcessingDate"=>"2015-04-21T10:09:14+00:00", "ReportRequestId"=>"50366016546"}, "HasNext"=>"false"}

**Comment by hakanensari** [comment]
The way I read it, requested to and from delimit when you requested a report, which is the submitted date. You use that to tell Amazon to give you reports requested in the past week, etc.

The start and end dates must have to do with the data in each report, which you set when you request a report.

A bit confusing, but everything seems to be OK. At least, Peddler is passing around the data fine :smile:

**Comment by gardart** [comment]
Ok, I read it like it should filter against the start and end range inside
the report.
I wanted to get a list of all the reports that are available with specific
time range (start_date and end_date) :)

And Yes, Peddler is passing around the data fine :)

Thanks again !

On Wed, Apr 22, 2015 at 3:39 PM, Hakan Ensari <notifications@github.com>
wrote:

> The way I read it, requested to and from delimit when you requested a
> report, which is the submitted date. You use that to tell Amazon to give
> you reports requested in the past week, etc.
>
> The start and end dates must have to do with the data in each report,
> which you set when you request a report.
>
> A bit confusing, but everything seems to be OK. At least, Peddler is
> passing around the data fine [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hakanensari/peddler/issues/37#issuecomment-95240611>.
>



-- 

Garðar Þorsteinsson | +354 693 9347
