### ISSUE TITLE
submit feeds to different marketplaces always end up to origin marketplace

### ISSUE THREAD

**Issue by stravas** [hakanensari/peddler#40]
Hello again,

I'm currently uploading products to my origin marketplace germany. I'm trying to update amazon products in different countries in europe.  I can't use **marketplace_id_list**, cause I'm making my own translations of my products. Like in your instruction i've changed the value of primary_marketplace_id to the marketplace-ID of the country I want to update in. The result is that no matter which marketplace-ID I'm giving to the client, the submit end up in my origin marketplace germany.

```ruby
MWS.feeds(
              primary_marketplace_id: "", <--- tried ES, FR and UK
              merchant_id:  XXX,
              aws_access_key_id: XXX,
              aws_secret_access_key: XXX
              )
```

I thought maybe there is a problem with the MWS-API. So I wrote the MWS-support. They gave me the request that I've sended. It looked like this:

```
02 Jul 2015 11:36:53,568 [DEBUG] d6477694-5377-4ce1-a75e-46438051023f: request from
AWSAccessKeyId=XXX&
Action=SubmitFeed&
FeedType=_POST_FLAT_FILE_LISTINGS_DATA_&
SellerId=XXX&
Signature=XXX&
SignatureMethod=HmacSHA256&
SignatureVersion=2&
Timestamp=2015-07-02T11%3A36%3A20Z to POST 
```

They told me I have to give a marketplace-ID in my request. Do you have an idea why the marketplace-ID is missing in the request?

For info: I have a europe selleraccount and I'm authorized to sell in the other countries.

Thank you for helping.

best regards stravas

**Comment by hakanensari** [comment]
I believe you still have to provide the marketplace id list with the marketplace you are uploading to.

**Comment by stravas** [comment]
I solved it.

The solution:
```ruby
client.submit_feed(latin_1_string, '_POST_FLAT_FILE_LISTINGS_DATA_', {marketplace_id_list: ["A1F83G8C2ARO7P"]}).parse
```

like hakanensari wrote you have to provide the marketplace id within the marketplace id list although it is just one value. It's an array with one value which is needed when you're selling in foreign marketplaces.

Thank hakanensari

**Comment by hakanensari** [comment]
:+1:
