### ISSUE TITLE
Bad Request when trying to get list of orders

### ISSUE THREAD

**Issue by ssoulless** [hakanensari/peddler#45]
Hey the above is my code:

```ruby
client = MWS::Orders::Client.new(
  primary_marketplace_id:ENV['MARKETPLACE_ID'],
  merchant_id:           ENV['MERCHANT_ID'],
  aws_access_key_id:     ENV['AWS_ACCESS_KEY_ID'],
  aws_secret_access_key: ENV['AWS_SECRET_ACCESS_KEY']
)

puts client.list_orders
```

Im trying to get the list of orders, it is not working it shows:
`response_call': Expected(200) <=> Actual(400 Bad Request) (Excon::Errors::BadRequest)
`
I tried

```ruby 
puts client.list_orders()
```

but did not work, what am I doing wrong?, is mandatory send options?

**Comment by ssoulless** [comment]
I also tried
```ruby
puts client.list_orders(created_before: Time.now.utc.iso8601)
```

But same result...

**Comment by hakanensari** [comment]
What's the error message?

```ruby
begin
  client.list_orders
rescue => e
  puts e.response.message
end
```

**Comment by ssoulless** [comment]
Hi this is the error message:
```
CreatedAfter or LastUpdatedAfter must be specified
```
but I do not understand, what it means, what am I missing?

**Comment by ssoulless** [comment]
Hi I found the issue, I read Amazon MWS and it seems that you have to send the created_after argument mandatory:

```ruby
client.list_orders(created_after: '2014-01-01')
```
Now it works, would be good if you add that detail to the docs, I mean add which ones are mandatory and which ones are not.

**Comment by hakanensari** [comment]
You're right. I'll add a note to the docs.
