### ISSUE TITLE
Support for "GetLowestPricedOffersForSKU"

### ISSUE THREAD

**Issue by mfelix** [hakanensari/peddler#50]
Hello! Recently I stumbled upon this function called [GetLowestPricedOffersForSKU](http://docs.developer.amazonservices.com/en_MX/products/Products_GetLowestPricedOffersForSKU.html) in Products section of MWS, and it looks like it was [recently added to other client libraries](http://docs.developer.amazonservices.com/en_MX/products/Products_ClientLibraries.html), so maybe it's new?

I dug through the documentation for this gem and couldn't find a method for it. Can you please update this gem to support it? I'm trying to figure out how to do it myself, but I've never written a gem before and am having a bit of trouble. Thanks for your consideration!

**Comment by hakanensari** [comment]
Good catch! This is indeed new—and strange.

From what I see, the response is essentially the same as [GetLowestOfferListingsForSKU][1] but includes Buy Box data, plus the hourly quota is significantly lower than the former. They seem not to want people to use this to fetch Buy Box data (of stuff they don't list) in bulk.

I'll add this ASAP.

[1]: http://docs.developer.amazonservices.com/en_MX/products/Products_GetLowestOfferListingsForSKU.html

**Comment by mfelix** [comment]
👏thank you!
