### ISSUE TITLE
Need a bit of help with the address format in create_inbound_shipment_plan

### ISSUE THREAD

**Issue by Trimakas** [hakanensari/peddler#52]
I've been trying with different versions of this hash, but can't get it to work!!! Any help is MUCH appreciated..

ship_from_address = {
  "Name" => "Company name",
  "AddressLine1" => "929 Whatever Dr.",
  "City" => "My Town",
  "StateOrProvinceCode" => "YY",
  "PostalCode" => "12345"
}

I know the client is setup correctly, I can request other more simple info from the API.. just my address format is somehow wrong I think!!

**Comment by hakanensari** [comment]
StackOverflow is a better place to troubleshoot implementation issues.

Here, you may be missing a required element in Address, for instance.
