### ISSUE TITLE
MWS US and DE  report api response 'Cp1252' instead of 'ISO-8859-1'

### ISSUE THREAD

**Issue by wppurking** [hakanensari/peddler#53]
@hakanensari 
I see the file [marketplace.rb](https://github.com/hakanensari/peddler/blob/master/lib/peddler/marketplace.rb#L30) have assign the response encoding to `Peddler::Parser` like `FlatFileParser`.

But i found recently amazon (US, DE) has change the report api (flat file) encoding from 'ISO-8859-1' to 'Cp1252' and i found [this article](http://www.i18nqa.com/debug/table-iso8859-1-vs-windows-1252.html)

These affect something like this:

```ruby
s = "™"
s.encoding #>#<Encoding:UTF-8>

s.encode('cp1252') #>"\x99"

s.encode('ISO-8859-1') #>Encoding::UndefinedConversionError: U+2122 from UTF-8 to ISO-8859-1....
```

So i think we should move [ISO-8859-1](https://github.com/hakanensari/peddler/blob/master/lib/peddler/marketplace.rb#L38) to Cp1252. Cp1252 can hold all char in iso-8859-1and some other latin chars.

attach with some response returned with Amazon Scratchpad
(I only have US and DE account for amaozn mws, so only test US and DE market)
![Amazon DE](https://cloud.githubusercontent.com/assets/448364/12002035/3c029406-ab30-11e5-8f40-2d834851cfa5.jpg)
![Amazon US](https://cloud.githubusercontent.com/assets/448364/12002037/470a6248-ab30-11e5-97ca-72243e3f4ded.jpg)

And response header with `EXCON_DEBUG=true`
![qq20151225-4](https://cloud.githubusercontent.com/assets/448364/12002074/0acd8570-ab31-11e5-81bc-dc091b9dd7eb.jpg)

**Comment by hakanensari** [comment]
I'll bump library version after confirming this is not messing with flat file uploads using the Feeds API.

**Comment by wppurking** [comment]
:+1:
