### ISSUE TITLE
Change docs for  get_lowest_priced_offers_for_sku/asin

### ISSUE THREAD

**Issue by zayka** [hakanensari/peddler#58]
Double get_lowest_priced_offers_for_sku
![skuasin](https://cloud.githubusercontent.com/assets/1076266/13488319/88dc8f20-e131-11e5-8bb7-08b4d1032c07.png)
 here 
http://www.rubydoc.info/github/hakanensari/peddler/MWS/Products/Client

**Comment by hakanensari** [comment]
Thanks @zayka
