### ISSUE TITLE
MWS::Reports::Client.request_report doesnt work as according to spec

### ISSUE THREAD

**Issue by czhu12** [hakanensari/peddler#60]
`client.request_report('_GET_FLAT_FILE_OPEN_LISTINGS_DATA_', marketplace_id_list: ['ATVPDKIKX0DER'])` 
throws a 
`Peddler::Marketplace::BadId: missing MarketplaceId`

When I set
`client.primary_marketplace_id = "ATVPDKIKX0DER"`
and run the command again, it throws a 
`ArgumentError: Missing secret`

**Comment by hakanensari** [comment]
It sounds like you're not instantiating the client with the proper credentials. Check the [README](https://github.com/hakanensari/peddler#usage) on how to do this.

**Comment by czhu12** [comment]
I set all the credentials in the environment. The other mws endpoints work it seems, but `request_report` is failing.

**Comment by hakanensari** [comment]
I can't reproduct this error.

I have requested above report with no issue using an active seller account.

**Comment by powellmichael** [comment]
I can't reproduce this error either.

**Comment by hakanensari** [comment]
:+1: I'll close
