### ISSUE TITLE
Problem with Products->get_product_categories_for_asin

### ISSUE THREAD

**Issue by pictona** [hakanensari/peddler#63]
Hi

When I try and call either method for getting categories for Products I always seem to get this error:

`undefined method `update' for "A1F83G8C2ARO7P":String`

line of code calling this is :
`client.get_product_categories_for_asin(asin, marketplace_code).parse`

I can use the same code but change to get_matching_product_for_asin and it will return results. It looks as though it is any method that just accepts a single sku or asin where it is not working as I tried with

`get_lowest_priced_offers_for_sku`

And the same error occurs.

There is also two methods in the Products section named the same:

`#get_lowest_priced_offers_for_sku(asin, item_condition, opts = { marketplace_id: primary_marketplace_id }) ⇒ Peddler::XMLParser`

`#get_lowest_priced_offers_for_sku(seller_sku, item_condition, opts = { marketplace_id: primary_marketplace_id }) ⇒ Peddler::XMLParser`

Thanks

**Comment by hakanensari** [comment]
The correct syntax would be `client.get_product_categories_for_asin(asin, marketplace_id: marketplace_code).parse`.

The documentation typo is already fixed in master.

**Comment by pictona** [comment]
Thanks
