### ISSUE TITLE
Does not support GetMyFeesEstimate for Products API

### ISSUE THREAD

**Issue by bdsimmons** [hakanensari/peddler#65]
[GetMyFeesEstimate](http://docs.developer.amazonservices.com/en_US/products/Products_GetMyFeesEstimate.html) is not currently present in the Products client, but is a really useful call. Any reason you are not supporting it currently?

**Comment by nsheepgi** [comment]
It is there now

**Comment by ifritz7** [comment]
I am trying to use GetMyFeesEstimate and my hash is not being accepted. Could someone show me an example hash for GetMyFeesEstimate? 

Thanks!!!

**Comment by sabatsu** [comment]
Same here...
I keep on getting:
Peddler::Errors::MalformedInput: Unexpected complex element termination
