### ISSUE TITLE
get_my_fees_estimate documentation  

### ISSUE THREAD

**Issue by ifritz7** [hakanensari/peddler#72]
Hello,

I am trying to use get_my_fees_estimate in the docs it says to submit a hash with request details. My hash looks like this:  {"MarketplaceId": 'ATVPDKIKX0DER', "IdType": "ASIN", "IdValue": "B01CVGV66W", "PriceToEstimateFees": 39.73, "Identifier": Time.now, "IsAmazonFulfilled": "true"}

My parsed return looks like this: 
{"FeesEstimateResultList"=>{"FeesEstimateResult"=>{"FeesEstimateIdentifier"=>{"SellerId"=>"A20YSPW1I1I0OV", "IsAmazonFulfilled"=>"false", "SellerInputIdentifier"=>"2016-09-20T12:33:32-04:00"}, "Error"=>{"Code"=>"InvalidParameterValue", "Message"=>"IdType cannot be empty.", "Type"=>"Sender"}, "Status"=>"ClientError"}}}

As you can see the "IsAmazonFulfilled"=>"false" when I tried to set it to true.

What am I doing wrong?

Could someone please post an example hash in the docs?

Thanks!!!

**Comment by hakanensari** [comment]
Try underscored symbols in your argument. That's `:marketplace_id` in place of `"MarketplaceId".

**Comment by ifritz7** [comment]
Thank you, it worked!!

Isaiah Fritzinger
