### ISSUE TITLE
New Parameter for SubmitFeed

### ISSUE THREAD

**Issue by machineboy2045** [hakanensari/peddler#77]
I got a notice from Amazon recently:

> Amazon Marketplace Web Service (Amazon MWS) is announcing a change to how MD5 hashes work for the SubmitFeed operation in the Feeds service. Previously, the MD5 hash for the incoming feed data was carried in the Content-MD5 header. This still works for backward compatibility, but we recommend passing the hash value using the ContentMD5Value parameter of SubmitFeed. This new parameter is available worldwide.
> When you pass the MD5 hash as a parameter, the value of the hash will be computed as part of the digital signature when submitting a feed. This will allow MWS to detect if the value has been modified in transit. GetFeedSubmissionResult still uses the Content-MD5 header as before.
> This change is reflected in the latest version of the Feeds client libraries, which you can download in the following languages:
> Java
> C#
> PHP

It says the change will be backwards compatible, so I assume peddler will keep working without an update. But I thought I'd post this just in case. :)

**Comment by hakanensari** [comment]
@machineboy2045 I will reopen. Being short of time, I had originally :+1:'ed the issue instead of replying, which probably was not very communicative.

Yes, let's implement this. Would you like to take a stab?

**Comment by machineboy2045** [comment]
Haha. No worries. I might take a stab but no promises. :P

**Comment by noorani786** [comment]
Did you guys get a chance to work on this?  Amazon is now throwing errors on this for the _POST_FLAT_FILE_PRICEANDQUANTITYONLY_UPDATE_DATA_

**Comment by hakanensari** [comment]
Yep, see linked commit above

**Comment by noorani786** [comment]
Sorry just not familiar with GitHub I guess.  I am only seeing config file changes:

<img width="1047" alt="screen shot 2018-02-22 at 3 49 27 pm" src="https://user-images.githubusercontent.com/1447852/36566101-1ced8338-17e8-11e8-89dd-770580cf683e.png">

**Comment by hakanensari** [comment]
You got me there. I actually implemented this in a dependency:

https://github.com/hakanensari/jeff/commit/d3a8d35eeaf41f279665a6fa42636aa1b8229d76 

I'll also change the version requirement for Jeff to reflect this, now that the deprecated header no longer works.

**Comment by noorani786** [comment]
Got it.  Thanks!
