### ISSUE TITLE
quota headers

### ISSUE THREAD

**Issue by chrishough** [hakanensari/peddler#80]
According to [AWS Throttling](https://docs.developer.amazonservices.com/en_DE/dev_guide/DG_Throttling.html) the following headers should come over with each request.
```
x-mws-quota-max: 3600
x-mws-quota-remaining: 10
x-mws-quota-resetsOn: Wed, 06 Mar 2013 19:07:58 GMT
```
Have these been removed from this gem?

**Comment by hakanensari** [comment]
They haven't been removed, as in they're there in the header, but we're not really exposing them in the crafted response.

Making this data more accessible could be a future improvement.

**Comment by chrishough** [comment]
I think passing them through would be more supportive of a API service layer.  Would it be cool if I sent you a PR for this?

**Comment by hakanensari** [comment]
Absolutely :cool:

**Comment by chrishough** [comment]
Thank you.  Sorry I have not had more time to work on this. I still have the other issue pending for verification.
