### ISSUE TITLE
amazon fees

### ISSUE THREAD

**Issue by chrishough** [hakanensari/peddler#81]
I have been researching this in the gem, and I am not seeing it but maybe AWS does not expose the transaction fees for orders / order items.  Thoughts? Happy to collab on this too.

**Comment by hakanensari** [comment]
You're on the right track in the other issue.

Also, I can't tell you which report type off the top of my head, but I'm pretty sure there's an order report that lists fees, so you may want to research in that direction as well.

**Comment by chrishough** [comment]
All I could find was this http://docs.developer.amazonservices.com/en_US/finances/Finances_Overview.html or this http://docs.developer.amazonservices.com/en_US/products/Products_GetMyFeesEstimate.html which was only for estimates.  What are you using to pull fees for orders purchased?
