### ISSUE TITLE
Get Report for Specific Marketplace always returns UK data

### ISSUE THREAD

**Issue by pictona** [hakanensari/peddler#85]
Hi,

I am trying to get inventory report data in the different marketplaces. I am setting the marketplace_id with the request and confirm the correct marketplace_code is in request to Amazon. Every time the report comes back though, it is showing the data from our UK (primary) marketplace. 

I use the exact same credentials and marketplace_code on the scratchpad and I get the report from the country requested. If I copy the generated report Id from the scratchpad request and run it through my get report code in rails, I see the correct country report.

I have tried debugging through the code, but can't seem to find why the correct report for the marketplace requested is not being returned.

Any idea?
Thanks

**Comment by pictona** [comment]
here is the client details when requesting report from italian marketplace:

--- !ruby/object:MWS::Reports::Client
primary_marketplace_id: APJ6JRA9NG5V4
merchant_id: XXXXXXXXXXXXX
aws_access_key_id: XXXXXXXXXXXXXXXXXXX
aws_secret_access_key: XXXXXXXXXXXXXXXXXX

--- !ruby/object:Excon::Response
data:
  :body: |
    <?xml version="1.0"?>
    <RequestReportResponse xmlns="http://mws.amazonaws.com/doc/2009-01-01/">
      <RequestReportResult>
        <ReportRequestInfo>
          <ReportType>_GET_MERCHANT_LISTINGS_DATA_</ReportType>
          <ReportProcessingStatus>_SUBMITTED_</ReportProcessingStatus>
          <EndDate>2017-01-20T13:12:36+00:00</EndDate>
          <Scheduled>false</Scheduled>
          <ReportRequestId>XXXXXXXXXX</ReportRequestId>
          <SubmittedDate>2017-01-20T13:12:36+00:00</SubmittedDate>
          <StartDate>2017-01-20T13:12:36+00:00</StartDate>
        </ReportRequestInfo>
      </RequestReportResult>
      <ResponseMetadata>
        <RequestId>XXXXXXXX</RequestId>
      </ResponseMetadata>
    </RequestReportResponse>
  :cookies: []
  :host: mws-eu.amazonservices.com
  :headers: &1 !ruby/hash:Excon::Headers


Thanks

**Comment by hakanensari** [comment]
It sounds like you're not providing the marketplace ID correctly when [requesting the report](http://www.rubydoc.info/gems/peddler/MWS%2FReports%2FClient%3Arequest_report) so it's defaulting to your home marketplace.

You can see your actual request if you set EXCON_DEBUG env var to true.
