### ISSUE TITLE
Encoding Issue

### ISSUE THREAD

**Issue by jxdx** [hakanensari/peddler#88]
sku = 'Küche 7pcs MultiColor Utensil Set'

response = request.get_matching_product_for_id('SellerSKU', *skus)

response.parse

{"Error"=>{"Type"=>"Sender", "Code"=>"InvalidParameterValue", "Message"=>"KÃ¼che 7pcs MultiColor Utensil Set is an invalid SellerSKU for marketplace ATVPDKIKX0DER"}, "Id"=>"KÃ¼che 7pcs MultiColor Utensil Set", "IdType"=>"SellerSKU", "status"=>"ClientError"}

Notice the first word KÃ¼che has strange characters in it. I need the response to have the same SKU that I sent, is there anyway to convert this back?

**Comment by hakanensari** [comment]
What version of jeff are you using? A [recent commit there](https://github.com/hakanensari/peddler/issues/84) may have fixed what you're describing.

**Comment by jxdx** [comment]
peddler (1.0.2)
      jeff (~> 1.3)
      multi_xml (~> 0.5.0)

**Comment by jxdx** [comment]
Updating my peddler version fixed the issue.
Thank you
