### ISSUE TITLE
Marketplace ID for PrimeNow DE missing

### ISSUE THREAD

**Issue by QuAcK3RjAcK** [hakanensari/peddler#90]
I'm working with PrimeNowDE marketplace and I got the marketplace ID "A1KU16HT7ALXJ0" from Amazon with the endpoint 'mws.amazonservices.de'.

Cause peddler doesn't know this new marketplace it always calls this Error: "A1KU16HT7ALXJ0" is not a valid MarketplaceId

Can you pls add the marketplace ID fpr PrimeNow DE to the HOSTS constant?
https://github.com/hakanensari/peddler/blob/master/lib/peddler/marketplace.rb

'A1KU16HT7ALXJ0'  => 'mws.amazonservices.de'

**Comment by hakanensari** [comment]
Hi @QuAcK3RjAcK ,

The [MWS docs](https://docs.developer.amazonservices.com/en_US/dev_guide/DG_Endpoints.html) do not mention `A1KU16HT7ALXJ0` as a valid marketplace ID. If this is a new, undocumented feature, can you point me to any resource online?

Also, have you tried using the regular German marketplace ID or alternatively, monkey-patching the HOSTS constant to try out your ID and see if it works?

**Comment by QuAcK3RjAcK** [comment]
Hi @hakanensari ,

Unfortunatly i don't have any online resource for that. My company started a partnership to sell over PrimeNow in Germany and i only have direct contact with them. They give me that Marketplace ID for PrimeNowDE. They said, that PrimeNow has also different marketplace IDs for different countries, but i only know the DE one.

I monkey patched the HOSTS constant and it was working. I also tested different endpoints like 'mw.amazonserivces.de' and 'mws-eu.amazonservices.com' and both worked, but they said i should use the first one. But when i read the docs about the endpoints it should be 'mws-eu...'.

In general the PrimeNow feature seems a bit undocumented, maybe because its very new. I think in Germany it starts a few months ago.

I will write to them with the hint to update your mentioned site.

**Comment by prathip111** [comment]
If there is any api for seller and customer messaging service?
