### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by alexfalkowski** [hakanensari/peddler#94]
Hi, 

Thanks for the great library. We are using `MWS::Reports::Client`. When we 

```ruby
get_report('ID').body
```

I can see that  text comes back as `für`

Though when we call 

```ruby
get_report('ID').parse.to_a
```

We get the text `fÃ¼r`

Seems to me something is using the wrong encoding. Maybe then CSV parsing is causing it?

**Comment by hakanensari** [comment]
Just to confirm, are you using the latest version?

**Comment by alexfalkowski** [comment]
From my Gemfile lock `peddler (1.6.1)`

**Comment by alexfalkowski** [comment]
So I think I find the issue

https://github.com/hakanensari/peddler/blob/b0be32d167f096d0e696e29f0091771e82eed200/lib/peddler/flat_file_parser.rb#L37

```ruby
irb(main):020:0> body.encoding == 'UTF-8'
=> false
irb(main):021:0> body.encoding
=> #<Encoding:UTF-8>
irb(main):022:0> body.encoding == Encoding::UTF_8
=> true
```

So that line should be:

```ruby
body.force_encoding(Encoding::UTF_8) unless body.encoding == Encoding::UTF_8
```

This is using ruby 2

**Comment by alexfalkowski** [comment]
So it looks like when I force the encoding the parsing works correctly.

**Comment by alexfalkowski** [comment]
So is it forcing the wrong encoding?

**Comment by alexfalkowski** [comment]
So this fixes is for me

```ruby
module Peddler::FlatFileParserExtensions
  def scrub_body!(_)
    body.force_encoding(Encoding::UTF_8) unless body.encoding == Encoding::UTF_8
  end
end

class Peddler::FlatFileParser
  prepend Peddler::FlatFileParserExtensions
end
```

**Comment by hakanensari** [comment]
Thanks, @alexfalkowski. I pushed your fix to master.

**Comment by alexfalkowski** [comment]
Thank you!
