### ISSUE TITLE
create_shipment method returning 404

### ISSUE THREAD

**Issue by mjthompsgb** [hakanensari/peddler#97]
I am having issues with the `create_shipment` method returning a 404 no matter what I do. I've used Peddler for a while and have had great luck with everything else but this won't work.

Trying something like this `create_shipment(o.shipment.info, rate[:offer_id])`

Getting `Excon::Error::NotFound: Expected(200) <=> Actual(404 Not Found)` no matter what.

Any ideas?

Thanks in advance.

**Comment by hakanensari** [comment]
Rescue the error and check its response body to see if there is a hint?

**Comment by mjthompsgb** [comment]
Awesome...thanks for the quick reply. Check that and getting `ShippingServiceNotAvailable` but going to do some more testing and see if the error code varies.

Thanks again.
