### ISSUE TITLE
How do subscriptions actually work?

### ISSUE THREAD

**Issue by philsmy** [hakanensari/peddler#98]
There is no documentation about this area and I think it's slightly complex.

I've registered a destination. But when I try to send a test I get an error:

subs.send_test_notification_to_destination("https://xxx.ngrok.io/amazon_sns_receiver")
Excon::Error::HTTPStatus: Expected(200) <=> Actual(424 Unknown)

Perhaps this is outside the scope of peddler, but, I can't find any information on what we actually need to register (what kind of url) and how we are supposed to deal with it. The Peddler tests are all just mocks.

**Comment by hakanensari** [comment]
@philsmy I missed this issue. I'm assuming you would have sorted this out by now, but basically you create a [SQS queue](https://aws.amazon.com/sqs/) and provide its URL here.

**Comment by philsmy** [comment]
Actually, I gave up on it. 
So, I went to SQS and created a queue. The Queue url is something like this:
```https://sqs.us-east-1.amazonaws.com/<number>/my-test-q```

What are the steps required to get anything sent to this? Because in my testing I never got a single message, even on a very active Amazon account. Do I have to register a destination? Create a subscription? What exactly.

Does anyone actually use this part of peddler and if so...for what? It would be nice to be pushed information instead of all the pulling we're doing.

**Comment by hakanensari** [comment]
Once you set up the destination, you have to create a subscription. Notifications then should start rolling in in real time.

(We use this to get price notifications.)

**Comment by AnkitRathore175** [comment]
HI @guys
I have a query instead,
I want to trigger the same kind of event on price changes or offer changes, and referring this doc http://docs.developer.amazonservices.com/en_CA/subscriptions/Subscriptions_Overview.html
I have registered the destinations and subscribed as well.
Now my question is that, how can i just trigger an event for any offer change event, so I can see the real payload and perform the appropriate actions at mine end?
thanks in advance
